// src/surfaces/CaptureMenu.tsx
import { useEffect, useRef, useState } from "react";
import { listen } from "@tauri-apps/api/event";
import {
  CalendarClock,
  Check,
  LockKeyhole,
  LoaderCircle,
  NotebookPen,
  Send,
  Undo2,
  X,
} from "lucide-react";
import {
  commitCapture,
  discardCapture,
  getCapturePreview,
  getVaultStatus,
  initializeVault,
  recordMemoCapture,
  resolvePlanTime,
  stashCapture,
  undoSecretStash,
  unlockVault,
  type PlanItem,
  type SelectionSnapshot,
  type VaultStatus,
} from "../api";

export default function CaptureMenu() {
  const [snapshot, setSnapshot] = useState<SelectionSnapshot | null>(null);
  const [plan, setPlan] = useState<PlanItem | null>(null);
  const [answer, setAnswer] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [resultMessage, setResultMessage] = useState("");
  const [vaultStatus, setVaultStatus] = useState<VaultStatus>({
    initialized: false,
    unlocked: false,
    secretCount: 0,
  });
  const [vaultAuthVisible, setVaultAuthVisible] = useState(false);
  const [masterPassword, setMasterPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [stashedSecretId, setStashedSecretId] = useState("");
  const [activeAction, setActiveAction] = useState<
    "feed" | "memo" | "stash" | ""
  >("");
  const closeTimer = useRef<number>();

  function clearCloseTimer() {
    if (closeTimer.current !== undefined)
      window.clearTimeout(closeTimer.current);
    closeTimer.current = undefined;
  }
  function reset() {
    clearCloseTimer();
    setSnapshot(null);
    setPlan(null);
    setAnswer("");
    setError("");
    setResultMessage("");
    setVaultAuthVisible(false);
    setMasterPassword("");
    setConfirmPassword("");
    setStashedSecretId("");
  }
  function closeAfter(delay: number) {
    clearCloseTimer();
    closeTimer.current = window.setTimeout(() => {
      void discardCapture().finally(reset);
    }, delay);
  }

  useEffect(() => {
    let disposed = false;
    let unlisten: (() => void) | undefined;
    void Promise.all([getCapturePreview(), getVaultStatus()]).then(
      ([preview, vault]) => {
        if (!disposed) {
          setSnapshot(preview);
          setVaultStatus(vault);
        }
      },
    );
    void listen<SelectionSnapshot>("capture-prepared", ({ payload }) => {
      setSnapshot(payload);
      setPlan(null);
      setAnswer("");
      setError("");
      setResultMessage("");
      setVaultAuthVisible(false);
      setMasterPassword("");
      setConfirmPassword("");
      setStashedSecretId("");
    }).then((stop) => {
      if (disposed) stop();
      else unlisten = stop;
    });
    return () => {
      disposed = true;
      unlisten?.();
      clearCloseTimer();
    };
  }, []);

  async function reject() {
    if (busy) return;
    clearCloseTimer();
    await discardCapture();
    reset();
  }
  async function feed() {
    if (busy || !snapshot) return;
    setBusy(true);
    setActiveAction("feed");
    setError("");
    try {
      const result = await commitCapture();
      setPlan(result.plan ?? null);
      if (!result.needsClarification) {
        setResultMessage(result.message);
        closeAfter(1400);
      }
    } catch (reason) {
      setError(String(reason));
    } finally {
      setBusy(false);
      setActiveAction("");
    }
  }
  async function remember() {
    if (busy || !snapshot) return;
    setBusy(true);
    setActiveAction("memo");
    setError("");
    try {
      const result = await recordMemoCapture();
      setResultMessage(result.message);
      setSnapshot(null);
      closeAfter(1400);
    } catch (reason) {
      setError(String(reason));
    } finally {
      setBusy(false);
      setActiveAction("");
    }
  }
  async function stashNow() {
    setBusy(true);
    setActiveAction("stash");
    setError("");
    try {
      const result = await stashCapture();
      setStashedSecretId(result.secretId);
      setResultMessage(result.message);
      setSnapshot(null);
      closeAfter(7600);
    } catch (reason) {
      setError(String(reason));
    } finally {
      setBusy(false);
      setActiveAction("");
    }
  }
  async function stash() {
    if (busy || !snapshot) return;
    if (!vaultStatus.unlocked) {
      setVaultAuthVisible(true);
      return;
    }
    await stashNow();
  }
  async function authorizeVaultAndStash() {
    if (!masterPassword || busy) return;
    if (!vaultStatus.initialized && masterPassword !== confirmPassword) {
      setError("两次主密码不一致");
      return;
    }
    setBusy(true);
    setActiveAction("stash");
    setError("");
    try {
      const status = vaultStatus.initialized
        ? await unlockVault(masterPassword)
        : await initializeVault(masterPassword);
      setVaultStatus(status);
      setMasterPassword("");
      setConfirmPassword("");
      setVaultAuthVisible(false);
    } catch (reason) {
      setError(String(reason));
      setBusy(false);
      setActiveAction("");
      return;
    }
    setBusy(false);
    setActiveAction("");
    await stashNow();
  }
  async function undoStash() {
    if (!stashedSecretId || busy) return;
    setBusy(true);
    try {
      await undoSecretStash(stashedSecretId);
      setResultMessage("已撤销");
      setStashedSecretId("");
      closeAfter(800);
    } catch (reason) {
      setError(String(reason));
    } finally {
      setBusy(false);
    }
  }
  async function submitTime(event: React.FormEvent) {
    event.preventDefault();
    if (busy || !plan || !answer.trim()) return;
    setBusy(true);
    setError("");
    try {
      const result = await resolvePlanTime(plan.id, answer.trim());
      setPlan(result.plan ?? null);
      setAnswer("");
      if (!result.needsClarification) {
        setResultMessage(result.message);
        closeAfter(1000);
      }
    } catch (reason) {
      setError(String(reason));
    } finally {
      setBusy(false);
    }
  }

  return (
    <section className="capture-popover" aria-label="处理选区">
      <header>
        <div className="surface-mark">
          <CalendarClock size={17} />
        </div>
        <strong>
          {resultMessage ? "处理完成" : plan ? "安排时间" : "处理选区"}
        </strong>
        <button
          className="icon-button"
          type="button"
          title="关闭"
          aria-label="关闭"
          onClick={() => void reject()}
        >
          <X size={17} />
        </button>
      </header>
      {resultMessage ? (
        <div className="capture-success">
          <span>
            <Check size={20} />
          </span>
          <strong>{resultMessage}</strong>
          {stashedSecretId && (
            <button
              className="undo-stash"
              type="button"
              disabled={busy}
              onClick={() => void undoStash()}
            >
              <Undo2 size={13} />
              撤销
            </button>
          )}
        </div>
      ) : plan?.status === "needs_clarification" ? (
        <>
          <p className="question">{plan.clarificationQuestion}</p>
          <form className="time-answer" onSubmit={submitTime}>
            <input
              value={answer}
              onChange={(e) => setAnswer(e.target.value)}
              maxLength={500}
              autoFocus
              placeholder="例如：明天下午 3 点"
            />
            <button
              type="submit"
              title="确认时间"
              aria-label="确认时间"
              disabled={busy || !answer.trim()}
            >
              {busy ? (
                <LoaderCircle className="spin" size={16} />
              ) : (
                <Check size={16} />
              )}
            </button>
          </form>
        </>
      ) : vaultAuthVisible ? (
        <form
          className="vault-auth"
          onSubmit={(e) => {
            e.preventDefault();
            void authorizeVaultAndStash();
          }}
        >
          <p>
            {vaultStatus.initialized
              ? "输入主密码以解锁秘密备忘录"
              : "设置独立主密码，丢失后无法从本机恢复"}
          </p>
          <input
            value={masterPassword}
            onChange={(e) => setMasterPassword(e.target.value)}
            type="password"
            minLength={6}
            maxLength={256}
            autoFocus
            autoComplete="off"
            placeholder="主密码（至少 6 个字符）"
          />
          {!vaultStatus.initialized && (
            <input
              value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
              type="password"
              minLength={6}
              maxLength={256}
              autoComplete="off"
              placeholder="再次输入主密码"
            />
          )}
          <button
            className="feed-button"
            type="submit"
            disabled={busy || masterPassword.length < 6}
          >
            {busy ? (
              <LoaderCircle className="spin" size={15} />
            ) : (
              <span>
                {vaultStatus.initialized ? "解锁并藏入" : "创建并藏入"}
              </span>
            )}
          </button>
        </form>
      ) : (
        <>
          <blockquote>{snapshot?.selectedText || "正在读取选区..."}</blockquote>
          <div className="feed-actions">
            <button
              className="feed-button"
              type="button"
              title="交给 AI 处理"
              disabled={busy || !snapshot}
              onClick={() => void feed()}
            >
              {busy && activeAction === "feed" ? (
                <LoaderCircle className="spin" size={15} />
              ) : (
                <>
                  <Send size={14} />
                  <span>喂</span>
                </>
              )}
            </button>
            <button
              className="memo-button"
              type="button"
              title="记入普通备忘录并同步飞书"
              disabled={busy || !snapshot}
              onClick={() => void remember()}
            >
              {busy && activeAction === "memo" ? (
                <LoaderCircle className="spin" size={15} />
              ) : (
                <>
                  <NotebookPen size={14} />
                  <span>记</span>
                </>
              )}
            </button>
            <button
              className="stash-button"
              type="button"
              title="藏入加密秘密备忘录"
              disabled={busy || !snapshot}
              onClick={() => void stash()}
            >
              {busy && activeAction === "stash" ? (
                <LoaderCircle className="spin" size={15} />
              ) : (
                <>
                  <LockKeyhole size={14} />
                  <span>藏</span>
                </>
              )}
            </button>
          </div>
        </>
      )}
      {error && <p className="surface-error">{error}</p>}
    </section>
  );
}

// src/surfaces/CaptureMenu.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from "vue";
import { listen, type UnlistenFn } from "@tauri-apps/api/event";
import { CalendarClock, Check, LockKeyhole, LoaderCircle, NotebookPen, Send, Undo2, X } from "lucide-vue-next";
import {
  commitCapture,
  discardCapture,
  getCapturePreview,
  getVaultStatus,
  initializeVault,
  resolvePlanTime,
  recordMemoCapture,
  stashCapture,
  undoSecretStash,
  unlockVault,
  type PlanItem,
  type SelectionSnapshot,
  type VaultStatus,
} from "../api";

const snapshot = ref<SelectionSnapshot | null>(null);
const plan = ref<PlanItem | null>(null);
const answer = ref("");
const busy = ref(false);
const error = ref("");
const resultMessage = ref("");
const vaultStatus = ref<VaultStatus>({ initialized: false, unlocked: false, secretCount: 0 });
const vaultAuthVisible = ref(false);
const masterPassword = ref("");
const confirmPassword = ref("");
const stashedSecretId = ref("");
const activeAction = ref<"feed" | "memo" | "stash" | "">("");
let unlisten: UnlistenFn | undefined;
let closeTimer: number | undefined;

onMounted(async () => {
  snapshot.value = await getCapturePreview();
  vaultStatus.value = await getVaultStatus();
  unlisten = await listen<SelectionSnapshot>("capture-prepared", (event) => {
    snapshot.value = event.payload;
    plan.value = null;
    answer.value = "";
    error.value = "";
    resultMessage.value = "";
    vaultAuthVisible.value = false;
    masterPassword.value = "";
    confirmPassword.value = "";
    stashedSecretId.value = "";
  });
});

onBeforeUnmount(() => {
  unlisten?.();
  if (closeTimer) window.clearTimeout(closeTimer);
});

async function reject(): Promise<void> {
  if (busy.value) return;
  clearCloseTimer();
  await discardCapture();
  reset();
}

async function feed(): Promise<void> {
  if (busy.value || !snapshot.value) return;
  busy.value = true;
  activeAction.value = "feed";
  error.value = "";
  try {
    const result = await commitCapture();
    plan.value = result.plan ?? null;
    if (!result.needsClarification) {
      resultMessage.value = result.message;
      closeTimer = window.setTimeout(async () => {
        await discardCapture();
        reset();
      }, 1400);
    }
  } catch (reason) {
    error.value = String(reason);
  } finally {
    busy.value = false;
    activeAction.value = "";
  }
}

async function stash(): Promise<void> {
  if (busy.value || !snapshot.value) return;
  if (!vaultStatus.value.unlocked) {
    vaultAuthVisible.value = true;
    return;
  }
  await stashNow();
}

async function remember(): Promise<void> {
  if (busy.value || !snapshot.value) return;
  busy.value = true;
  activeAction.value = "memo";
  error.value = "";
  try {
    const result = await recordMemoCapture();
    resultMessage.value = result.message;
    snapshot.value = null;
    closeTimer = window.setTimeout(async () => {
      await discardCapture();
      reset();
    }, 1400);
  } catch (reason) {
    error.value = String(reason);
  } finally {
    busy.value = false;
    activeAction.value = "";
  }
}

async function authorizeVaultAndStash(): Promise<void> {
  if (!masterPassword.value || busy.value) return;
  if (!vaultStatus.value.initialized && masterPassword.value !== confirmPassword.value) {
    error.value = "两次主密码不一致";
    return;
  }
  busy.value = true;
  activeAction.value = "stash";
  error.value = "";
  try {
    vaultStatus.value = vaultStatus.value.initialized
      ? await unlockVault(masterPassword.value)
      : await initializeVault(masterPassword.value);
    masterPassword.value = "";
    confirmPassword.value = "";
    vaultAuthVisible.value = false;
  } catch (reason) {
    error.value = String(reason);
    busy.value = false;
    activeAction.value = "";
    return;
  }
  busy.value = false;
  activeAction.value = "";
  await stashNow();
}

async function stashNow(): Promise<void> {
  busy.value = true;
  activeAction.value = "stash";
  error.value = "";
  try {
    const result = await stashCapture();
    stashedSecretId.value = result.secretId;
    resultMessage.value = result.message;
    snapshot.value = null;
    closeTimer = window.setTimeout(async () => {
      await discardCapture();
      reset();
    }, 7600);
  } catch (reason) {
    error.value = String(reason);
  } finally {
    busy.value = false;
    activeAction.value = "";
  }
}

async function undoStash(): Promise<void> {
  if (!stashedSecretId.value || busy.value) return;
  busy.value = true;
  try {
    await undoSecretStash(stashedSecretId.value);
    resultMessage.value = "已撤销";
    stashedSecretId.value = "";
    closeTimer = window.setTimeout(async () => {
      await discardCapture();
      reset();
    }, 800);
  } catch (reason) {
    error.value = String(reason);
  } finally {
    busy.value = false;
  }
}

async function submitTime(): Promise<void> {
  if (busy.value || !plan.value || !answer.value.trim()) return;
  busy.value = true;
  error.value = "";
  try {
    const result = await resolvePlanTime(plan.value.id, answer.value.trim());
    plan.value = result.plan ?? null;
    answer.value = "";
    if (!result.needsClarification) {
      resultMessage.value = result.message;
      closeTimer = window.setTimeout(reset, 1000);
    }
  } catch (reason) {
    error.value = String(reason);
  } finally {
    busy.value = false;
  }
}

function reset(): void {
  clearCloseTimer();
  snapshot.value = null;
  plan.value = null;
  answer.value = "";
  error.value = "";
  resultMessage.value = "";
  vaultAuthVisible.value = false;
  masterPassword.value = "";
  confirmPassword.value = "";
  stashedSecretId.value = "";
}

function clearCloseTimer(): void {
  if (closeTimer !== undefined) {
    window.clearTimeout(closeTimer);
    closeTimer = undefined;
  }
}
</script>

<template>
  <section class="capture-popover" aria-label="处理选区">
    <header>
      <div class="surface-mark"><CalendarClock :size="17" /></div>
      <strong>{{ resultMessage ? "处理完成" : plan ? "安排时间" : "处理选区" }}</strong>
      <button class="icon-button" type="button" title="关闭" aria-label="关闭" @click="reject">
        <X :size="17" />
      </button>
    </header>

    <div v-if="resultMessage" class="capture-success">
      <span><Check :size="20" /></span>
      <strong>{{ resultMessage }}</strong>
      <button v-if="stashedSecretId" class="undo-stash" type="button" :disabled="busy" @click="undoStash">
        <Undo2 :size="13" />撤销
      </button>
    </div>

    <template v-else-if="plan?.status === 'needs_clarification'">
      <p class="question">{{ plan.clarificationQuestion }}</p>
      <form class="time-answer" @submit.prevent="submitTime">
        <input v-model="answer" maxlength="500" autofocus placeholder="例如：明天下午 3 点" />
        <button type="submit" title="确认时间" aria-label="确认时间" :disabled="busy || !answer.trim()">
          <LoaderCircle v-if="busy" class="spin" :size="16" />
          <Check v-else :size="16" />
        </button>
      </form>
    </template>

    <form v-else-if="vaultAuthVisible" class="vault-auth" @submit.prevent="authorizeVaultAndStash">
      <p>{{ vaultStatus.initialized ? "输入主密码以解锁秘密备忘录" : "设置独立主密码，丢失后无法从本机恢复" }}</p>
      <input v-model="masterPassword" type="password" minlength="6" maxlength="256" autofocus autocomplete="off" placeholder="主密码（至少 6 个字符）" />
      <input v-if="!vaultStatus.initialized" v-model="confirmPassword" type="password" minlength="6" maxlength="256" autocomplete="off" placeholder="再次输入主密码" />
      <button class="feed-button" type="submit" :disabled="busy || masterPassword.length < 6">
        <LoaderCircle v-if="busy" class="spin" :size="15" />
        <span v-else>{{ vaultStatus.initialized ? "解锁并藏入" : "创建并藏入" }}</span>
      </button>
    </form>

    <template v-else>
      <blockquote>{{ snapshot?.selectedText || "正在读取选区..." }}</blockquote>
      <div class="feed-actions">
        <button class="feed-button" type="button" title="交给 AI 处理" :disabled="busy || !snapshot" @click="feed">
          <LoaderCircle v-if="busy && activeAction === 'feed'" class="spin" :size="15" />
          <template v-else><Send :size="14" /><span>喂</span></template>
        </button>
        <button class="memo-button" type="button" title="记入普通备忘录并同步飞书" :disabled="busy || !snapshot" @click="remember">
          <LoaderCircle v-if="busy && activeAction === 'memo'" class="spin" :size="15" />
          <template v-else><NotebookPen :size="14" /><span>记</span></template>
        </button>
        <button class="stash-button" type="button" title="藏入加密秘密备忘录" :disabled="busy || !snapshot" @click="stash">
          <LoaderCircle v-if="busy && activeAction === 'stash'" class="spin" :size="15" />
          <template v-else><LockKeyhole :size="14" /><span>藏</span></template>
        </button>
      </div>
    </template>
    <p v-if="error" class="surface-error">{{ error }}</p>
  </section>
</template>
